### ISSUE TITLE
Improve project documentation

### ISSUE THREAD

**Issue by leobiscassi** [rodrigofaccioli/drugdesign#12]
Hi @rodrigofaccioli, what you think about improve the README.md document? For instance, give more instructions about how to install the dependencies and to execute the algorithm in all the ways possible (Python, Spark, C). If you are according with this, I would like help on this task.

**Comment by rodrigofaccioli** [comment]
Hi @leobiscassi, your suggestion was great. 
Please, feel free for starting this improvement. 
Best.

**Comment by leobiscassi** [comment]
ok @rodrigofaccioli! here we go! :smiley:

**Comment by leobiscassi** [comment]
Closing this *issue* for any question about this, see PR [#21](https://github.com/rodrigofaccioli/drugdesign/pull/21)
