### ISSUE TITLE
Preparing drugdesign version 1.0

### ISSUE THREAD

**Issue by rodrigofaccioli** [rodrigofaccioli/drugdesign#20]
@leobiscassi @Hakory 
Please, let me know it is ok we create the Drugdesign release 1.0 until October, 25 (next Tuesday) ?

After that, I would like to work on two specific issues:
1) Working on Python 3.0 instead of Python 2.7
2) Working on Spark 2.0 instead of Spark 1.6

The Drugdesign release 1.1 will be created based on these above new features. 

Starting NoSQL model through Cassandra and Big Table.

**Comment by leobiscassi** [comment]
Hi @rodrigofaccioli @Hakory, sounds good for me.

**Comment by Hakory** [comment]
Yo @rodrigofaccioli @leobiscassi,  "sounds good" indeed :smile: . And we can schedule a Hangout to talk about the two issues if needed.
