### ISSUE TITLE
Preparing box

### ISSUE THREAD

**Issue by rodrigofaccioli** [rodrigofaccioli/drugdesign#29]
@Hakory 
preparing_box.py file is failed when I try to run it. 
I've crated test/virtual_screening/vina/prepare_box directory that contains the files I have used. Could you check it ?

**Comment by Hakory** [comment]
@rodrigofaccioli I ran the tests and they worked perfectly. Please try upgrading the version of Gromacs to 5.1.4, if that does not work check the file /home/faccioli/Programs/MGLTools-1.5.6/bin/pythonsh, possibly the MGL_ROOT environment variable is wrong path and Pythonsh is not running. Let me know if it works 😃

**Comment by rodrigofaccioli** [comment]
@Hakory 
Now it is working.
